-- Run this in Supabase SQL editor to create reservations table
create table if not exists reservations (
  id bigint generated by default as identity primary key,
  name text,
  date date,
  time text,
  guests int,
  note text,
  created_at timestamptz default now()
);
